config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get("/", { :controller => "articles", :action => "index" })


  root "places#index"

    resources :places, only: [:index, :show, :new, :create] do
    resources :entries, only: [:new, :create] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  # talks to the "entries" table
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  # talks to the "places" table
  
    has_many :entries
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @place = Place.find(params[:place_id])
    @entry = @place.entries.build
  end

  def create
    @place = Place.find(params[:place_id])
    @entry = @place.entries.build(entry_params)

    if @entry.save
      redirect_to place_path(@place), notice: "Entry added successfully!"
    else
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :date)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path, notice: "Place added successfully!"
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>Add a New Entry for <%= @place.name %></h1>

<%= form_with model: [@place, @entry], local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
  <%= form.submit "Save Entry" %>
<% end %>

<p><%= link_to "Back to Place", place_path(@place) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places I've Visited</h1>
<ul>
  <% @places.each do |place| %>
    <li><%= link_to place.name, place_path(place) %></li>
  <% end %>
</ul>
<%= link_to "Add New Place", new_place_path %>

app/views/places/new.html.erb
<h1>Add a New Place</h1>

<%= form_with model: @place, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "Save Place" %>
<% end %>

<p><%= link_to "Back to Places", places_path %></p>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>
<p><%= link_to "Back to Places", places_path %></p>

<h2>Entries</h2>
<ul>
  <% @entries.each do |entry| %>
    <li><strong><%= entry.title %></strong> - <%= entry.date %></li>
  <% end %>
</ul>

<%= link_to "Add Entry", new_place_entry_path(@place) %>